apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: connected-vehicle
  labels:
    app: platform-secrets
type: Opaque
stringData:
  POSTGRES_DB: telemetry
  POSTGRES_USER: fleet
  POSTGRES_PASSWORD: fleetpass
  SPRING_DATASOURCE_USERNAME: fleet
  SPRING_DATASOURCE_PASSWORD: fleetpass
  GRAFANA_USER: admin
  GRAFANA_PASSWORD: admin
